/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateYourSongRouteImport } from './routes/create-your-song'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as MusicIndexRouteImport } from './routes/music.index'
import { Route as MusicSlugRouteImport } from './routes/music.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateYourSongRoute = CreateYourSongRouteImport.update({
  id: '/create-your-song',
  path: '/create-your-song',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicSlugRoute = MusicSlugRouteImport.update({
  id: '/music/$slug',
  path: '/music/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/create-your-song': typeof CreateYourSongRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music/': typeof MusicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/create-your-song': typeof CreateYourSongRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music': typeof MusicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/create-your-song': typeof CreateYourSongRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/music/$slug': typeof MusicSlugRoute
  '/music/': typeof MusicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/contact'
    | '/create-your-song'
    | '/privacy'
    | '/releases'
    | '/terms'
    | '/videos'
    | '/music/$slug'
    | '/music/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/contact'
    | '/create-your-song'
    | '/privacy'
    | '/releases'
    | '/terms'
    | '/videos'
    | '/music/$slug'
    | '/music'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/contact'
    | '/create-your-song'
    | '/privacy'
    | '/releases'
    | '/terms'
    | '/videos'
    | '/music/$slug'
    | '/music/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CreateYourSongRoute: typeof CreateYourSongRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleasesRoute: typeof ReleasesRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  MusicSlugRoute: typeof MusicSlugRoute
  MusicIndexRoute: typeof MusicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-your-song': {
      id: '/create-your-song'
      path: '/create-your-song'
      fullPath: '/create-your-song'
      preLoaderRoute: typeof CreateYourSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/$slug': {
      id: '/music/$slug'
      path: '/music/$slug'
      fullPath: '/music/$slug'
      preLoaderRoute: typeof MusicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CreateYourSongRoute: CreateYourSongRoute,
  PrivacyRoute: PrivacyRoute,
  ReleasesRoute: ReleasesRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  MusicSlugRoute: MusicSlugRoute,
  MusicIndexRoute: MusicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
